var algorithmJSONList=[
       			{
    				name:'数据清理算法',
    				actionName:'DataCleanAction',
    				introduction:'清理数据的算法',
    				param:[
    					{name:'清理的列',field:'rowNum',type:'Integer'}
    				]
    			},
    			{
    				name:'贝叶斯算法',
    				actionName:'BayesAction',
    				introduction:'R语言中的关于贝叶斯的一种算法',
    				param:[
    					{name:'是否包含表头',field:'hasheader',type:'Boolean'},
    					{name:'公式',field:'formula',type:'String'}
    				]
    			}
    			];